CUDA_VISIBLE_DEBVISES=0 python run.py \
    --prefix codenet \
    --output_dir ../saved_models/inference \
    --data_cache_dir ../saved_models/inference \
    --eval_data_path ../data/codenetmut_test.json \
    --model_name_or_path microsoft/codeexecutor \
    --block_size 1024 \
    --per_gpu_train_batch_size 8 \
    --per_gpu_eval_batch_size 16 \
    --gradient_accumulation_steps 8 \
    --learning_rate 1e-4 \
    --node_index 0 \
    --weight_decay 0.01 \
    --adam_epsilon 1e-6 \
    --max_grad_norm 1.0 \
    --max_steps 1000 \
    --warmup_steps 10000 \
    --save_steps 5000 \
    --seed 123456